import type { Catalog } from "./types";

export const catalog: Catalog = {
  cpus: [
    {
      id: "cpu-7800x3d",
      kind: "cpu",
      name: "AMD Ryzen 7 7800X3D",
      brand: "AMD",
      price: { currency: "USD", amount: 399 },
      socket: "AM5",
      cores: 8,
      threads: 16,
      baseClockGhz: 4.2,
      boostClockGhz: 5.0,
      tdpW: 120,
      benchmarks: {
        gamingScore: 2050,
        singleCoreScore: 1920,
        multiCoreScore: 14800,
      },
    },
    {
      id: "cpu-14700k",
      kind: "cpu",
      name: "Intel Core i7-14700K",
      brand: "Intel",
      price: { currency: "USD", amount: 409 },
      socket: "LGA1700",
      cores: 20,
      threads: 28,
      baseClockGhz: 3.4,
      boostClockGhz: 5.6,
      tdpW: 125,
      benchmarks: {
        gamingScore: 1850,
        singleCoreScore: 1980,
        multiCoreScore: 20600,
      },
    },
    {
      id: "cpu-7600",
      kind: "cpu",
      name: "AMD Ryzen 5 7600",
      brand: "AMD",
      price: { currency: "USD", amount: 229 },
      socket: "AM5",
      cores: 6,
      threads: 12,
      baseClockGhz: 3.8,
      boostClockGhz: 5.1,
      tdpW: 65,
      benchmarks: {
        gamingScore: 1550,
        singleCoreScore: 1750,
        multiCoreScore: 11200,
      },
    },
  ],
  gpus: [
    {
      id: "gpu-4080s",
      kind: "gpu",
      name: "NVIDIA GeForce RTX 4080 SUPER",
      brand: "NVIDIA",
      price: { currency: "USD", amount: 999 },
      vramGb: 16,
      tdpW: 320,
      benchmarks: {
        rasterScore: 2600,
        rayTracingScore: 2400,
      },
    },
    {
      id: "gpu-7900xtx",
      kind: "gpu",
      name: "AMD Radeon RX 7900 XTX",
      brand: "AMD",
      price: { currency: "USD", amount: 949 },
      vramGb: 24,
      tdpW: 355,
      benchmarks: {
        rasterScore: 2450,
        rayTracingScore: 1850,
      },
    },
    {
      id: "gpu-4070s",
      kind: "gpu",
      name: "NVIDIA GeForce RTX 4070 SUPER",
      brand: "NVIDIA",
      price: { currency: "USD", amount: 599 },
      vramGb: 12,
      tdpW: 220,
      benchmarks: {
        rasterScore: 2050,
        rayTracingScore: 1800,
      },
    },
  ],
  motherboards: [
    {
      id: "mb-b650e-rog",
      kind: "motherboard",
      name: "ASUS ROG STRIX B650E-F Gaming WiFi",
      brand: "ASUS",
      price: { currency: "USD", amount: 269 },
      socket: "AM5",
      chipset: "B650E",
      formFactor: "ATX",
      memoryStandard: "DDR5",
      maxMemoryGb: 192,
      pcieGen: 5,
    },
    {
      id: "mb-z790-tomahawk",
      kind: "motherboard",
      name: "MSI MAG Z790 TOMAHAWK WiFi",
      brand: "MSI",
      price: { currency: "USD", amount: 259 },
      socket: "LGA1700",
      chipset: "Z790",
      formFactor: "ATX",
      memoryStandard: "DDR5",
      maxMemoryGb: 192,
      pcieGen: 5,
    },
    {
      id: "mb-b550-aorus",
      kind: "motherboard",
      name: "Gigabyte B550 AORUS ELITE",
      brand: "Gigabyte",
      price: { currency: "USD", amount: 149 },
      socket: "AM4",
      chipset: "B550",
      formFactor: "ATX",
      memoryStandard: "DDR4",
      maxMemoryGb: 128,
      pcieGen: 4,
    },
    {
      id: "mb-z890-maximus-hero",
      kind: "motherboard",
      name: "ASUS ROG Maximus Z890 Hero",
      brand: "ASUS",
      price: { currency: "USD", amount: 599 },
      socket: "LGA1851",
      chipset: "Z890",
      formFactor: "ATX",
      memoryStandard: "DDR5",
      maxMemoryGb: 192,
      pcieGen: 5,
    },
    {
      id: "mb-z890-meg-godlike",
      kind: "motherboard",
      name: "MSI MEG Z890 Godlike",
      brand: "MSI",
      price: { currency: "USD", amount: 899 },
      socket: "LGA1851",
      chipset: "Z890",
      formFactor: "ATX",
      memoryStandard: "DDR5",
      maxMemoryGb: 192,
      pcieGen: 5,
    },
    {
      id: "mb-z890-strix-f",
      kind: "motherboard",
      name: "ASUS ROG Strix Z890-F Gaming WiFi",
      brand: "ASUS",
      price: { currency: "USD", amount: 429 },
      socket: "LGA1851",
      chipset: "Z890",
      formFactor: "ATX",
      memoryStandard: "DDR5",
      maxMemoryGb: 192,
      pcieGen: 5,
    },
    {
      id: "mb-x870-aorus-master",
      kind: "motherboard",
      name: "Gigabyte X870 AORUS Master",
      brand: "Gigabyte",
      price: { currency: "USD", amount: 549 },
      socket: "AM5",
      chipset: "X870",
      formFactor: "ATX",
      memoryStandard: "DDR5",
      maxMemoryGb: 192,
      pcieGen: 5,
    },
    {
      id: "mb-x870-rog-crosshair",
      kind: "motherboard",
      name: "ASUS ROG Crosshair X870E Hero",
      brand: "ASUS",
      price: { currency: "USD", amount: 649 },
      socket: "AM5",
      chipset: "X870E",
      formFactor: "ATX",
      memoryStandard: "DDR5",
      maxMemoryGb: 192,
      pcieGen: 5,
    },
  ],
  ramKits: [
    {
      id: "ram-ddr5-32-6000",
      kind: "ram",
      name: "G.Skill Trident Z5 Neo 32GB (2x16) DDR5-6000",
      brand: "G.Skill",
      price: { currency: "USD", amount: 129 },
      memoryStandard: "DDR5",
      capacityGb: 32,
      modules: 2,
      speedMhz: 6000,
      tdpW: 10,
    },
    {
      id: "ram-ddr4-32-3600",
      kind: "ram",
      name: "Corsair Vengeance LPX 32GB (2x16) DDR4-3600",
      brand: "Corsair",
      price: { currency: "USD", amount: 79 },
      memoryStandard: "DDR4",
      capacityGb: 32,
      modules: 2,
      speedMhz: 3600,
      tdpW: 8,
    },
    {
      id: "ram-ddr5-32-6000-cl30",
      kind: "ram",
      name: "G.Skill Trident Z5 RGB 32GB (2x16) DDR5-6000 CL30",
      brand: "G.Skill",
      price: { currency: "USD", amount: 159 },
      memoryStandard: "DDR5",
      capacityGb: 32,
      modules: 2,
      speedMhz: 6000,
      tdpW: 10,
    },
    {
      id: "ram-ddr5-64-6400",
      kind: "ram",
      name: "Corsair Dominator Titanium 64GB (2x32) DDR5-6400",
      brand: "Corsair",
      price: { currency: "USD", amount: 279 },
      memoryStandard: "DDR5",
      capacityGb: 64,
      modules: 2,
      speedMhz: 6400,
      tdpW: 12,
    },
    {
      id: "ram-ddr5-32-7200",
      kind: "ram",
      name: "G.Skill Trident Z5 RGB 32GB (2x16) DDR5-7200",
      brand: "G.Skill",
      price: { currency: "USD", amount: 219 },
      memoryStandard: "DDR5",
      capacityGb: 32,
      modules: 2,
      speedMhz: 7200,
      tdpW: 12,
    },
    {
      id: "ram-ddr5-32-8000",
      kind: "ram",
      name: "Corsair Dominator Titanium 32GB (2x16) DDR5-8000",
      brand: "Corsair",
      price: { currency: "USD", amount: 329 },
      memoryStandard: "DDR5",
      capacityGb: 32,
      modules: 2,
      speedMhz: 8000,
      tdpW: 14,
    },
  ],
  psus: [
    {
      id: "psu-focus-850",
      kind: "psu",
      name: "Seasonic FOCUS GX-850 (850W)",
      brand: "Seasonic",
      price: { currency: "USD", amount: 149 },
      wattageW: 850,
      efficiencyRating: "80+ Gold",
      modular: "full",
    },
    {
      id: "psu-rmx-1000",
      kind: "psu",
      name: "Corsair RMx Shift 1000W",
      brand: "Corsair",
      price: { currency: "USD", amount: 189 },
      wattageW: 1000,
      efficiencyRating: "80+ Platinum",
      modular: "full",
    },
    {
      id: "psu-650-gold",
      kind: "psu",
      name: "MSI MPG A650GF (650W)",
      brand: "MSI",
      price: { currency: "USD", amount: 89 },
      wattageW: 650,
      efficiencyRating: "80+ Gold",
      modular: "full",
    },
    {
      id: "psu-rog-thor-1200",
      kind: "psu",
      name: "ASUS ROG Thor 1200W ATX 3.1",
      brand: "ASUS",
      price: { currency: "USD", amount: 399 },
      wattageW: 1200,
      efficiencyRating: "80+ Platinum",
      modular: "full",
    },
    {
      id: "psu-corsair-hx1200i",
      kind: "psu",
      name: "Corsair HX1200i 1200W ATX 3.0",
      brand: "Corsair",
      price: { currency: "USD", amount: 349 },
      wattageW: 1200,
      efficiencyRating: "80+ Platinum",
      modular: "full",
    },
    {
      id: "psu-msi-a1000g",
      kind: "psu",
      name: "MSI MPG A1000G PCIe 5.0 (1000W)",
      brand: "MSI",
      price: { currency: "USD", amount: 219 },
      wattageW: 1000,
      efficiencyRating: "80+ Gold",
      modular: "full",
    },
    {
      id: "psu-green-gp1000",
      kind: "psu",
      name: "Green GP1000 (1000W) ATX 3.1",
      brand: "Green",
      price: { currency: "USD", amount: 189 },
      wattageW: 1000,
      efficiencyRating: "80+ Gold",
      modular: "full",
    },
  ],
};
