import type { Cpu, Gpu } from "./types";

export const sampleCpus: Cpu[] = [
  {
    id: "cpu-i9-14900k",
    kind: "cpu",
    name: "Intel Core i9-14900K",
    brand: "Intel",
    price: { currency: "USD", amount: 589 },
    socket: "LGA1700",
    cores: 24,
    threads: 32,
    baseClockGhz: 3.2,
    boostClockGhz: 6,
    tdpW: 125,
    benchmarks: {
      gamingScore: 2150,
      singleCoreScore: 2100,
      multiCoreScore: 23000,
    },
  },
  {
    id: "cpu-i7-14700k",
    kind: "cpu",
    name: "Intel Core i7-14700K",
    brand: "Intel",
    price: { currency: "USD", amount: 419 },
    socket: "LGA1700",
    cores: 20,
    threads: 28,
    baseClockGhz: 3.4,
    boostClockGhz: 5.6,
    tdpW: 125,
    benchmarks: {
      gamingScore: 2000,
      singleCoreScore: 1950,
      multiCoreScore: 21500,
    },
  },
  {
    id: "cpu-i5-14600k",
    kind: "cpu",
    name: "Intel Core i5-14600K",
    brand: "Intel",
    price: { currency: "USD", amount: 339 },
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    baseClockGhz: 3.5,
    boostClockGhz: 5.3,
    tdpW: 125,
    benchmarks: {
      gamingScore: 1850,
      singleCoreScore: 1850,
      multiCoreScore: 18000,
    },
  },
  {
    id: "cpu-i5-14500",
    kind: "cpu",
    name: "Intel Core i5-14500",
    brand: "Intel",
    price: { currency: "USD", amount: 289 },
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    baseClockGhz: 2.6,
    boostClockGhz: 5,
    tdpW: 125,
    benchmarks: {
      gamingScore: 1700,
      singleCoreScore: 1750,
      multiCoreScore: 16000,
    },
  },
  {
    id: "cpu-i5-14400f",
    kind: "cpu",
    name: "Intel Core i5-14400F",
    brand: "Intel",
    price: { currency: "USD", amount: 249 },
    socket: "LGA1700",
    cores: 10,
    threads: 16,
    baseClockGhz: 2.5,
    boostClockGhz: 4.7,
    tdpW: 65,
    benchmarks: {
      gamingScore: 1550,
      singleCoreScore: 1650,
      multiCoreScore: 14000,
    },
  },
  {
    id: "cpu-i3-14100",
    kind: "cpu",
    name: "Intel Core i3-14100",
    brand: "Intel",
    price: { currency: "USD", amount: 149 },
    socket: "LGA1700",
    cores: 4,
    threads: 8,
    baseClockGhz: 3.5,
    boostClockGhz: 4.7,
    tdpW: 60,
    benchmarks: {
      gamingScore: 1250,
      singleCoreScore: 1400,
      multiCoreScore: 9000,
    },
  },
  {
    id: "cpu-ryzen9-9950x",
    kind: "cpu",
    name: "AMD Ryzen 9 9950X",
    brand: "AMD",
    price: { currency: "USD", amount: 699 },
    socket: "AM5",
    cores: 16,
    threads: 32,
    baseClockGhz: 4.3,
    boostClockGhz: 5.7,
    tdpW: 170,
    benchmarks: {
      gamingScore: 2250,
      singleCoreScore: 2150,
      multiCoreScore: 26000,
    },
  },
  {
    id: "cpu-ryzen9-9900x",
    kind: "cpu",
    name: "AMD Ryzen 9 9900X",
    brand: "AMD",
    price: { currency: "USD", amount: 549 },
    socket: "AM5",
    cores: 12,
    threads: 24,
    baseClockGhz: 4,
    boostClockGhz: 5.6,
    tdpW: 170,
    benchmarks: {
      gamingScore: 2150,
      singleCoreScore: 2100,
      multiCoreScore: 24000,
    },
  },
  {
    id: "cpu-ryzen9-7900x3d",
    kind: "cpu",
    name: "AMD Ryzen 9 7900X3D",
    brand: "AMD",
    price: { currency: "USD", amount: 499 },
    socket: "AM5",
    cores: 12,
    threads: 24,
    baseClockGhz: 4.4,
    boostClockGhz: 5.6,
    tdpW: 120,
    benchmarks: {
      gamingScore: 2100,
      singleCoreScore: 2050,
      multiCoreScore: 23000,
    },
  },
  {
    id: "cpu-ryzen7-9700x",
    kind: "cpu",
    name: "AMD Ryzen 7 9700X",
    brand: "AMD",
    price: { currency: "USD", amount: 399 },
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 3.8,
    boostClockGhz: 5.5,
    tdpW: 120,
    benchmarks: {
      gamingScore: 2050,
      singleCoreScore: 2000,
      multiCoreScore: 20000,
    },
  },
  {
    id: "cpu-7800x3d",
    kind: "cpu",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    price: { currency: "USD", amount: 399 },
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 4.2,
    boostClockGhz: 5,
    tdpW: 120,
    benchmarks: {
      gamingScore: 2050,
      singleCoreScore: 1920,
      multiCoreScore: 14800,
    },
  },
  {
    id: "cpu-ryzen7-7700x",
    kind: "cpu",
    name: "AMD Ryzen 7 7700X",
    brand: "AMD",
    price: { currency: "USD", amount: 329 },
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 4.5,
    boostClockGhz: 5.4,
    tdpW: 105,
    benchmarks: {
      gamingScore: 1900,
      singleCoreScore: 1850,
      multiCoreScore: 18000,
    },
  },
  {
    id: "cpu-ryzen5-9600x",
    kind: "cpu",
    name: "AMD Ryzen 5 9600X",
    brand: "AMD",
    price: { currency: "USD", amount: 279 },
    socket: "AM5",
    cores: 6,
    threads: 12,
    baseClockGhz: 4,
    boostClockGhz: 5.4,
    tdpW: 105,
    benchmarks: {
      gamingScore: 1750,
      singleCoreScore: 1800,
      multiCoreScore: 16000,
    },
  },
  {
    id: "cpu-ryzen5-7600",
    kind: "cpu",
    name: "AMD Ryzen 5 7600",
    brand: "AMD",
    price: { currency: "USD", amount: 229 },
    socket: "AM5",
    cores: 6,
    threads: 12,
    baseClockGhz: 3.8,
    boostClockGhz: 5.1,
    tdpW: 65,
    benchmarks: {
      gamingScore: 1600,
      singleCoreScore: 1700,
      multiCoreScore: 13500,
    },
  },
  {
    id: "cpu-i5-13400",
    kind: "cpu",
    name: "Intel Core i5-13400",
    brand: "Intel",
    price: { currency: "USD", amount: 239 },
    socket: "LGA1700",
    cores: 10,
    threads: 16,
    baseClockGhz: 2.5,
    boostClockGhz: 4.6,
    tdpW: 65,
    benchmarks: {
      gamingScore: 1500,
      singleCoreScore: 1650,
      multiCoreScore: 12500,
    },
  },
  {
    id: "cpu-ultra9-285k",
    kind: "cpu",
    name: "Intel Core Ultra 9 285K",
    brand: "Intel",
    price: { currency: "USD", amount: 799 },
    socket: "LGA1851",
    cores: 24,
    threads: 32,
    baseClockGhz: 3.3,
    boostClockGhz: 6.0,
    tdpW: 150,
    benchmarks: {
      gamingScore: 2400,
      singleCoreScore: 2250,
      multiCoreScore: 28000,
    },
  },
  {
    id: "cpu-ultra7-265k",
    kind: "cpu",
    name: "Intel Core Ultra 7 265K",
    brand: "Intel",
    price: { currency: "USD", amount: 599 },
    socket: "LGA1851",
    cores: 20,
    threads: 28,
    baseClockGhz: 3.4,
    boostClockGhz: 5.8,
    tdpW: 140,
    benchmarks: {
      gamingScore: 2250,
      singleCoreScore: 2150,
      multiCoreScore: 25000,
    },
  },
  {
    id: "cpu-ultra5-245k",
    kind: "cpu",
    name: "Intel Core Ultra 5 245K",
    brand: "Intel",
    price: { currency: "USD", amount: 449 },
    socket: "LGA1851",
    cores: 16,
    threads: 24,
    baseClockGhz: 3.5,
    boostClockGhz: 5.5,
    tdpW: 130,
    benchmarks: {
      gamingScore: 2100,
      singleCoreScore: 2050,
      multiCoreScore: 22000,
    },
  },
  {
    id: "cpu-ryzen7-9800x3d",
    kind: "cpu",
    name: "AMD Ryzen 7 9800X3D",
    brand: "AMD",
    price: { currency: "USD", amount: 549 },
    socket: "AM5",
    cores: 8,
    threads: 16,
    baseClockGhz: 4.3,
    boostClockGhz: 5.6,
    tdpW: 120,
    benchmarks: {
      gamingScore: 2350,
      singleCoreScore: 2100,
      multiCoreScore: 19000,
    },
  },
];

export type StoreProductCategory = "console" | "peripheral" | "prebuilt";

export type BaseStoreProduct = {
  id: string;
  name: string;
  category: StoreProductCategory;
  priceUsd: number;
  imageUrl: string;
  shortDescription: string;
  tags: string[];
};

export type ConsoleProduct = BaseStoreProduct & {
  category: "console";
  platform: "PS5" | "Xbox Series X" | "Nintendo Switch";
  storageGb: number;
  edition: string;
};

export type PeripheralKind = "keyboard" | "mouse" | "headset";

export type PeripheralProduct = BaseStoreProduct & {
  category: "peripheral";
  kind: PeripheralKind;
  rgb: boolean;
};

export type PrebuiltProduct = BaseStoreProduct & {
  category: "prebuilt";
  cpuName: string;
  gpuName: string;
  memoryGb: number;
  storage: string;
  targetUse: "esports" | "4k" | "creator";
};

export const sampleConsoles: ConsoleProduct[] = [
  {
    id: "console-ps5",
    name: "PlayStation 5 Disc Edition",
    category: "console",
    platform: "PS5",
    storageGb: 825,
    edition: "Standard",
    priceUsd: 499,
    imageUrl: "/images/consoles/ps5-standard.png",
    shortDescription: "4K HDR console with ray tracing and ultra fast SSD.",
    tags: ["4k", "ray tracing", "sony"],
  },
  {
    id: "console-ps5-slim-digital",
    name: "PlayStation 5 Slim Digital",
    category: "console",
    platform: "PS5",
    storageGb: 1000,
    edition: "Digital",
    priceUsd: 449,
    imageUrl: "/images/consoles/ps5-slim-digital.png",
    shortDescription: "Slim all digital PS5 with 1 TB SSD for next gen titles.",
    tags: ["digital", "slim", "sony"],
  },
  {
    id: "console-xsx",
    name: "Xbox Series X 1 TB",
    category: "console",
    platform: "Xbox Series X",
    storageGb: 1000,
    edition: "Standard",
    priceUsd: 499,
    imageUrl: "/images/consoles/xbox-series-x.png",
    shortDescription: "4K gaming with Game Pass ready out of the box.",
    tags: ["4k", "microsoft", "game pass"],
  },
  {
    id: "console-switch-oled",
    name: "Nintendo Switch OLED",
    category: "console",
    platform: "Nintendo Switch",
    storageGb: 64,
    edition: "OLED",
    priceUsd: 349,
    imageUrl: "/images/consoles/switch-oled.png",
    shortDescription: "Hybrid handheld console with vibrant OLED display.",
    tags: ["portable", "nintendo", "family"],
  },
];

export const samplePeripherals: PeripheralProduct[] = [
  {
    id: "peripheral-keyboard-tkl",
    name: "Titan Chroma TKL Mechanical Keyboard",
    category: "peripheral",
    kind: "keyboard",
    rgb: true,
    priceUsd: 169,
    imageUrl: "/images/peripherals/titan-chroma-tkl.png",
    shortDescription: "Compact TKL board with hot swap switches and per key RGB.",
    tags: ["mechanical", "rgb", "tkl"],
  },
  {
    id: "peripheral-mouse-esports",
    name: "Velocity Pro Wireless Mouse",
    category: "peripheral",
    kind: "mouse",
    rgb: false,
    priceUsd: 129,
    imageUrl: "/images/peripherals/velocity-pro-mouse.png",
    shortDescription: "Lightweight 55 g wireless mouse with 8 k polling.",
    tags: ["esports", "wireless", "low latency"],
  },
  {
    id: "peripheral-headset-surround",
    name: "Nebula 7.1 Gaming Headset",
    category: "peripheral",
    kind: "headset",
    rgb: true,
    priceUsd: 149,
    imageUrl: "/images/peripherals/nebula-headset.png",
    shortDescription: "Closed back headset with virtual 7.1 and broadcast mic.",
    tags: ["7.1", "rgb", "mic"],
  },
];

export const samplePrebuiltPcs: PrebuiltProduct[] = [
  {
    id: "prebuilt-esports-1440p",
    name: "Titan Esports 1440p",
    category: "prebuilt",
    cpuName: "Ryzen 5 7600",
    gpuName: "RTX 4070 SUPER class",
    memoryGb: 32,
    storage: "1 TB NVMe SSD",
    targetUse: "esports",
    priceUsd: 1899,
    imageUrl: "/images/prebuilt/titan-esports-1440p.png",
    shortDescription: "High refresh 1440p competitive rig tuned for FPS titles.",
    tags: ["1440p", "esports", "wifi6"],
  },
  {
    id: "prebuilt-4k-ultimate",
    name: "Titan 4K Ultimate",
    category: "prebuilt",
    cpuName: "Ryzen 7 7800X3D",
    gpuName: "RTX 4090 class",
    memoryGb: 64,
    storage: "2 TB NVMe SSD",
    targetUse: "4k",
    priceUsd: 3499,
    imageUrl: "/images/prebuilt/titan-4k-ultimate.png",
    shortDescription: "Cinematic 4K gaming and creator system with massive headroom.",
    tags: ["4k", "ray tracing", "creator"],
  },
  {
    id: "prebuilt-creator-studio",
    name: "Titan Creator Studio",
    category: "prebuilt",
    cpuName: "Intel Core i9 14900K",
    gpuName: "RTX 4080 class",
    memoryGb: 64,
    storage: "2 TB NVMe SSD + 4 TB HDD",
    targetUse: "creator",
    priceUsd: 3299,
    imageUrl: "/images/prebuilt/titan-creator-studio.png",
    shortDescription: "Workstation grade rig for editing, streaming and gaming.",
    tags: ["creator", "streaming", "workstation"],
  },
];

export const sampleGpus: Gpu[] = [
  {
    id: "gpu-rtx-5090",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 5090",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 1999 },
    vramGb: 32,
    tdpW: 520,
    benchmarks: {
      rasterScore: 3600,
      rayTracingScore: 3300,
    },
  },
  {
    id: "gpu-rtx-5080",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 5080",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 1399 },
    vramGb: 16,
    tdpW: 420,
    benchmarks: {
      rasterScore: 3200,
      rayTracingScore: 2950,
    },
  },
  {
    id: "gpu-rtx-5070ti",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 5070 Ti",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 999 },
    vramGb: 16,
    tdpW: 350,
    benchmarks: {
      rasterScore: 2900,
      rayTracingScore: 2700,
    },
  },
  {
    id: "gpu-rtx-5070",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 5070",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 799 },
    vramGb: 12,
    tdpW: 300,
    benchmarks: {
      rasterScore: 2700,
      rayTracingScore: 2500,
    },
  },
  {
    id: "gpu-rtx-5060ti",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 5060 Ti",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 599 },
    vramGb: 12,
    tdpW: 230,
    benchmarks: {
      rasterScore: 2350,
      rayTracingScore: 2150,
    },
  },
  {
    id: "gpu-rtx-5060",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 5060",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 449 },
    vramGb: 12,
    tdpW: 200,
    benchmarks: {
      rasterScore: 2150,
      rayTracingScore: 1900,
    },
  },
  {
    id: "gpu-rtx-5050",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 5050",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 349 },
    vramGb: 8,
    tdpW: 170,
    benchmarks: {
      rasterScore: 1900,
      rayTracingScore: 1700,
    },
  },
  {
    id: "gpu-rtx-4090",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4090",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 1599 },
    vramGb: 24,
    tdpW: 450,
    benchmarks: {
      rasterScore: 3000,
      rayTracingScore: 2700,
    },
  },
  {
    id: "gpu-rtx-4080-super",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4080 SUPER",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 1199 },
    vramGb: 16,
    tdpW: 320,
    benchmarks: {
      rasterScore: 2700,
      rayTracingScore: 2400,
    },
  },
  {
    id: "gpu-rtx-4080",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4080",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 1099 },
    vramGb: 16,
    tdpW: 320,
    benchmarks: {
      rasterScore: 2600,
      rayTracingScore: 2300,
    },
  },
  {
    id: "gpu-rtx-4070ti",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4070 Ti",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 799 },
    vramGb: 12,
    tdpW: 285,
    benchmarks: {
      rasterScore: 2300,
      rayTracingScore: 2000,
    },
  },
  {
    id: "gpu-rtx-4070-super",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4070 SUPER",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 699 },
    vramGb: 12,
    tdpW: 220,
    benchmarks: {
      rasterScore: 2200,
      rayTracingScore: 1900,
    },
  },
  {
    id: "gpu-rtx-4070",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4070",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 599 },
    vramGb: 12,
    tdpW: 200,
    benchmarks: {
      rasterScore: 2100,
      rayTracingScore: 1850,
    },
  },
  {
    id: "gpu-rtx-4060ti-16gb",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4060 Ti 16GB",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 499 },
    vramGb: 16,
    tdpW: 165,
    benchmarks: {
      rasterScore: 1950,
      rayTracingScore: 1700,
    },
  },
  {
    id: "gpu-rtx-4060ti",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4060 Ti",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 399 },
    vramGb: 8,
    tdpW: 160,
    benchmarks: {
      rasterScore: 1850,
      rayTracingScore: 1600,
    },
  },
  {
    id: "gpu-rtx-4060",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4060",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 329 },
    vramGb: 8,
    tdpW: 140,
    benchmarks: {
      rasterScore: 1650,
      rayTracingScore: 1450,
    },
  },
  {
    id: "gpu-rtx-4050",
    kind: "gpu",
    name: "NVIDIA GeForce RTX 4050",
    brand: "NVIDIA",
    price: { currency: "USD", amount: 279 },
    vramGb: 8,
    tdpW: 115,
    benchmarks: {
      rasterScore: 1450,
      rayTracingScore: 1250,
    },
  },
  {
    id: "gpu-7900xtx",
    kind: "gpu",
    name: "AMD Radeon RX 7900 XTX",
    brand: "AMD",
    price: { currency: "USD", amount: 949 },
    vramGb: 24,
    tdpW: 355,
    benchmarks: {
      rasterScore: 2650,
      rayTracingScore: 1900,
    },
  },
  {
    id: "gpu-7900xt",
    kind: "gpu",
    name: "AMD Radeon RX 7900 XT",
    brand: "AMD",
    price: { currency: "USD", amount: 799 },
    vramGb: 20,
    tdpW: 315,
    benchmarks: {
      rasterScore: 2500,
      rayTracingScore: 1800,
    },
  },
  {
    id: "gpu-7800xt",
    kind: "gpu",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    price: { currency: "USD", amount: 549 },
    vramGb: 16,
    tdpW: 260,
    benchmarks: {
      rasterScore: 2200,
      rayTracingScore: 1650,
    },
  },
  {
    id: "gpu-7700xt",
    kind: "gpu",
    name: "AMD Radeon RX 7700 XT",
    brand: "AMD",
    price: { currency: "USD", amount: 449 },
    vramGb: 12,
    tdpW: 245,
    benchmarks: {
      rasterScore: 2000,
      rayTracingScore: 1550,
    },
  },
  {
    id: "gpu-7600xt",
    kind: "gpu",
    name: "AMD Radeon RX 7600 XT",
    brand: "AMD",
    price: { currency: "USD", amount: 339 },
    vramGb: 16,
    tdpW: 190,
    benchmarks: {
      rasterScore: 1750,
      rayTracingScore: 1400,
    },
  },
  {
    id: "gpu-7600",
    kind: "gpu",
    name: "AMD Radeon RX 7600",
    brand: "AMD",
    price: { currency: "USD", amount: 269 },
    vramGb: 8,
    tdpW: 165,
    benchmarks: {
      rasterScore: 1600,
      rayTracingScore: 1300,
    },
  },
];
